# These are supported funding model platforms
github: [Varsha-1605]  # GitHub username
buy_me_a_coffee: varsha1605  # Your Buy Me a Coffee username
ko_fi: # Replace with a single Ko-fi username
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
custom: ['https://www.linkedin.com/in/varsha-dewangan-197983256']  # Additional contact/social links
