blank_issues_enabled: false
contact_links:
  - name: 💬 SocioSell Community Discussions
    url: https://github.com/Varsha-1605/SocioSell/discussions
    about: Please ask and answer questions in our community discussions
  
  - name: 📚 SocioSell Documentation
    url: https://github.com/Varsha-1605/SocioSell#readme
    about: Check our documentation for answers
    
  - name: 📧 Contact Support
    url: mailto:varshadewangan1605@gmail.com
    about: Contact the maintainer directly
